// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipmentService.Infrastructure.Data.Context;

#nullable disable

namespace ShipmentService.Infrastructure.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260302143853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EstimatedDaysMax")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days_max");

                    b.Property<int?>("EstimatedDaysMin")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days_min");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("MultiplierFee")
                        .HasColumnType("double precision")
                        .HasColumnName("multiplier_fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("SpeedLevel")
                        .HasColumnType("text")
                        .HasColumnName("speed_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Provider_Services", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("BulkyType")
                        .HasColumnType("text")
                        .HasColumnName("bulky_type");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryAddressId")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address_id");

                    b.Property<DateTime?>("DeliveryEstimatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_estimated_at");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<long>("FinalShippingFeeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("final_shipping_fee_cents");

                    b.Property<bool>("IsFreeShipping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free_shipping");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("PickupAddressId")
                        .HasColumnType("text")
                        .HasColumnName("pickup_address_id");

                    b.Property<DateTime?>("PickupScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_scheduled_at");

                    b.Property<Guid?>("ProviderServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<double>("TotalWeightGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("total_weight_grams");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ProviderServiceId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShippingProvider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("text")
                        .HasColumnName("support_email");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("text")
                        .HasColumnName("support_phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProviderId");

                    b.ToTable("Shipping_Providers", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.ShippingProvider", "ShippingProvider")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingProvider");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.ProviderService", "ProviderService")
                        .WithMany("Shipments")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShippingProvider", b =>
                {
                    b.Navigation("ProviderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
