// <auto-generated />
using System;
using ShipmentService.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShipmentService.Infrastructure.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    [Migration("20260225000001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_code");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderLogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("provider_logo_url");

                    b.Property<string>("ServiceCode")
                        .HasColumnType("text")
                        .HasColumnName("service_code");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<string>("SpeedLevel")
                        .HasColumnType("text")
                        .HasColumnName("speed_level");

                    b.Property<int?>("EstimatedDeliveryDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_delivery_days");

                    b.Property<string>("Limitations")
                        .HasColumnType("text")
                        .HasColumnName("limitations");

                    b.Property<string>("ZoneConfig")
                        .HasColumnType("text")
                        .HasColumnName("zone_config");

                    b.Property<string>("PricingRules")
                        .HasColumnType("text")
                        .HasColumnName("pricing_rules");

                    b.Property<string>("PlatformFeeConfig")
                        .HasColumnType("text")
                        .HasColumnName("platform_fee_config");

                    b.Property<bool>("IsActive")
                        .HasDefaultValue(true)
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriorityOrder")
                        .HasDefaultValue(0)
                        .HasColumnType("integer")
                        .HasColumnName("priority_order");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId");

                    b.ToTable("provider_services", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("ShipmentCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shipment_code");

                    b.Property<Guid?>("ProviderServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_service_id");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.Property<string>("PickupAddressId")
                        .HasColumnType("text")
                        .HasColumnName("pickup_address_id");

                    b.Property<string>("DeliveryAddressId")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address_id");

                    b.Property<double>("TotalWeightGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("total_weight_grams");

                    b.Property<double?>("TotalVolumeCm3")
                        .HasColumnType("double precision")
                        .HasColumnName("total_volume_cm3");

                    b.Property<int>("PackageCount")
                        .HasDefaultValue(1)
                        .HasColumnType("integer")
                        .HasColumnName("package_count");

                    b.Property<string>("BulkyType")
                        .IsRequired()
                        .HasDefaultValue("Normal")
                        .HasColumnType("text")
                        .HasColumnName("bulky_type");

                    b.Property<bool>("IsFragile")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<bool>("RequiresInsurance")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("requires_insurance");

                    b.Property<double>("InsuranceFeeCents")
                        .HasDefaultValue(0.0)
                        .HasColumnType("double precision")
                        .HasColumnName("insurance_fee_cents");

                    b.Property<long>("FinalShippingFeeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("final_shipping_fee_cents");

                    b.Property<bool>("IsFreeShipping")
                        .HasDefaultValue(false)
                        .HasColumnType("boolean")
                        .HasColumnName("is_free_shipping");

                    b.Property<DateTime?>("PickupScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_scheduled_at");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<DateTime?>("DeliveryEstimatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_estimated_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasDefaultValue("Pending")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("text")
                        .HasColumnName("customer_note");

                    b.Property<string>("InternalNote")
                        .HasColumnType("text")
                        .HasColumnName("internal_note");

                    b.Property<string>("DeliveryInstruction")
                        .HasColumnType("text")
                        .HasColumnName("delivery_instruction");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ShipmentCode")
                        .IsUnique();

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.HasIndex("ProviderServiceId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.ProviderService", "ProviderService")
                        .WithMany("Shipments")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
