// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipmentService.Infrastructure.Data.Context;

#nullable disable

namespace ShipmentService.Infrastructure.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    partial class ShipmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EstimatedDaysMax")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days_max");

                    b.Property<int?>("EstimatedDaysMin")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_days_min");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("MultiplierFee")
                        .HasColumnType("double precision")
                        .HasColumnName("multiplier_fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("SpeedLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("speed_level");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Provider_Services", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Provider_Services_code", "code IN ('ECO','STD','EXP','SUP')");

                            t.HasCheckConstraint("CHK_Provider_Services_speed_level", "speed_level IS NULL OR speed_level IN ('ECONOMY','STANDARD','EXPRESS','SUPER_EXPRESS')");
                        });
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("BulkyType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bulky_type");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryAddressId")
                        .HasColumnType("text")
                        .HasColumnName("delivery_address_id");

                    b.Property<DateTime?>("DeliveryEstimatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_estimated_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<long>("FinalShippingFeeVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("final_shipping_fee_cents");

                    b.Property<bool>("IsFreeShipping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free_shipping");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at");

                    b.Property<string>("PickupAddressId")
                        .HasColumnType("text")
                        .HasColumnName("pickup_address_id");

                    b.Property<DateTime?>("PickupScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_scheduled_at");

                    b.Property<Guid?>("ProviderServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<double>("TotalWeightGrams")
                        .HasColumnType("double precision")
                        .HasColumnName("total_weight_grams");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ShipmentId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Shipments_order_id");

                    b.HasIndex("ProviderServiceId");

                    b.HasIndex("TrackingNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Shipments_tracking_number")
                        .HasFilter("tracking_number IS NOT NULL");

                    b.ToTable("Shipments", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Shipments_bulky_type", "bulky_type IS NULL OR bulky_type IN ('NORMAL','BULKY','SUPER_BULKY')");

                            t.HasCheckConstraint("CHK_Shipments_status", "status IN ('DRAFT','PENDING','PICKUP_SCHEDULED','PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','DELIVERY_FAILED','RETURNING','RETURNED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShippingProvider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("support_email");

                    b.Property<string>("SupportPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("support_phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProviderId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Shipping_Providers_name");

                    b.ToTable("Shipping_Providers", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShopCache", b =>
                {
                    b.Property<Guid>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("DefaultPickupAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("default_pickup_address");

                    b.Property<Guid?>("DefaultProvider")
                        .HasColumnType("uuid")
                        .HasColumnName("default_provider");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.HasKey("ShopId");

                    b.ToTable("shop_cache", (string)null);
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.ShippingProvider", "ShippingProvider")
                        .WithMany("ProviderServices")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingProvider");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("ShipmentService.Domain.Entities.ProviderService", "ProviderService")
                        .WithMany("Shipments")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProviderService");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ProviderService", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("ShipmentService.Domain.Entities.ShippingProvider", b =>
                {
                    b.Navigation("ProviderServices");
                });
#pragma warning restore 612, 618
        }
    }
}
